theme: jekyll-theme-minimal
title: Michigan Applied Robotics Group (MARG)
description: MARG is designed to build an alliance organization to facilitate greater collaboration among the constituent teams and key stakeholders to ensure Michigan is the premier place for robotics.
logo: /assets/imgs/old-logo.jpg